import { SITE_URL } from "./clinic"

export type Faq = { q: string; a: string }

export type SeoPage = {
  slug: string
  title: string
  description: string
  h1: string
  intro: string
  primaryKeyword: string
  keywords: string[]
  /** Schema.org medical condition or procedure type for the structured data. */
  schemaType: "MedicalProcedure" | "MedicalCondition" | "MedicalTherapy" | "MedicalSpecialty"
  /** Optional MedicalCode or related condition for richer schema. */
  relatedConditions?: string[]
  services: { title: string; description: string }[]
  symptoms?: string[]
  whenToVisit: string[]
  treatmentApproach: string[]
  faqs: Faq[]
  ctaHeading: string
  ctaSubheading: string
}

const COMMON_FAQS: Faq[] = [
  {
    q: "How do I book an appointment at Shanti Nursing Home?",
    a: "You can book online through our appointment page, call +91-9410805042, or message us on WhatsApp. Same-day appointments are usually possible for clinic hours Mon–Sat 11 AM–3 PM and 6:30 PM–8 PM.",
  },
  {
    q: "Does Dr. Vinita Malhotra offer virtual / online consultations?",
    a: "Yes. Virtual consultations are available by appointment for follow-ups, second opinions, report review and many non-emergency concerns. You can request one when booking.",
  },
  {
    q: "Where is Shanti Nursing Home located in Saharanpur?",
    a: "Circular Road, opposite Private Ward, SBD Hospital, Prakashpuram, Saharanpur, Uttar Pradesh 247001. The clinic is centrally located and easy to reach from anywhere in the city.",
  },
]

export const seoPages: SeoPage[] = [
  {
    slug: "gynaecologist-saharanpur",
    title: "Best Gynaecologist in Saharanpur | Dr. Vinita Malhotra | Shanti Nursing Home",
    description:
      "Experienced gynaecologist in Saharanpur. Dr. Vinita Malhotra (MBBS, DGO) — practicing since 1996. Pap smears, PCOS, infections, menopause, period problems & more. Book online.",
    h1: "Expert Gynaecologist in Saharanpur",
    intro:
      "Looking for an experienced gynaecologist in Saharanpur? Dr. Vinita Malhotra has been caring for women in Saharanpur since 1996 with comprehensive gynaecological care — from your first Pap smear and period problems to PCOS, menopause and minor procedures, all under one roof at Shanti Nursing Home.",
    primaryKeyword: "gynaecologist in Saharanpur",
    keywords: [
      "gynaecologist in Saharanpur",
      "lady gynaecologist Saharanpur",
      "female gynaecologist Saharanpur",
      "gynae clinic Saharanpur",
      "Dr. Vinita Malhotra",
    ],
    schemaType: "MedicalSpecialty",
    services: [
      { title: "Annual Well-Woman Exam", description: "Complete checkup, Pap smear, breast exam and preventive screening tailored to your age and risk factors." },
      { title: "Menstrual Disorders", description: "Diagnosis and treatment for irregular, painful or heavy periods, PCOD / PCOS and hormonal imbalance." },
      { title: "Vaginal Infections & Discomfort", description: "Evaluation and treatment of vaginal infections, STIs, pelvic pain and chronic itching." },
      { title: "PCOS & Hormonal Care", description: "Lifestyle, medical and long-term management for polycystic ovary syndrome and metabolic concerns." },
      { title: "Menopause Management", description: "Symptom relief, bone health, hormone therapy guidance and lifestyle counselling." },
      { title: "Family Planning & Contraception", description: "Counselling for all contraceptive options including IUCD insertion, pills and emergency contraception." },
    ],
    symptoms: [
      "Irregular, missed, painful or unusually heavy periods",
      "Bleeding between periods or after intercourse",
      "Vaginal discharge, itching, burning or bad odour",
      "Pelvic pain, bloating or pressure",
      "Pain during intercourse",
      "Hot flashes, night sweats or mood swings",
      "Unwanted facial hair, acne or sudden weight gain (PCOS signs)",
      "Trouble conceiving for more than 6–12 months",
    ],
    whenToVisit: [
      "You're due for your annual checkup or Pap smear.",
      "Your periods have changed in pattern, flow or pain level.",
      "You suspect a urinary or vaginal infection.",
      "You're planning a pregnancy or starting contraception.",
      "You're approaching menopause and want a plan.",
      "You have a family history of breast, ovarian or cervical cancer.",
    ],
    treatmentApproach: [
      "Detailed history and unhurried consultation in a private, women-led clinic.",
      "Targeted investigations only when needed — ultrasound, hormonal profile, Pap smear, infection panel.",
      "Personalised treatment plan that fits your stage of life, goals and budget.",
      "Clear next-step counselling, written prescriptions and easy WhatsApp follow-up.",
    ],
    faqs: [
      { q: "Is Dr. Vinita Malhotra a female gynaecologist?", a: "Yes. Dr. Vinita Malhotra is a lady gynaecologist who has been practicing in Saharanpur since 1996, with extensive experience in obstetrics, gynaecology and vaginal surgery." },
      { q: "What is the consultation fee?", a: "Standard clinic consultation is affordable and transparent — please call +91-9410805042 or WhatsApp us for the current fee. Virtual consultation pricing is shared at the time of booking." },
      { q: "How often should I see a gynaecologist?", a: "Most women benefit from an annual well-woman visit, with a Pap smear every 3 years from age 21 (or as advised). See us sooner for any new symptom." },
      { q: "Do I need a referral to visit?", a: "No referral is required. You can book directly online, by phone or WhatsApp." },
      ...COMMON_FAQS,
    ],
    ctaHeading: "Need a Gynaecologist in Saharanpur?",
    ctaSubheading: "Book a consultation with Dr. Vinita Malhotra at Shanti Nursing Home — in person or online.",
  },
  {
    slug: "best-gynaecologist-saharanpur",
    title: "Best Gynaecologist in Saharanpur | Dr. Vinita Malhotra (Since 1996)",
    description:
      "Top-rated lady gynaecologist in Saharanpur — Dr. Vinita Malhotra, MBBS, DGO. 25+ years experience in obstetrics, gynaecology, infertility and vaginal surgery. Book today.",
    h1: "Best Gynaecologist in Saharanpur",
    intro:
      "When patients search for the best gynaecologist in Saharanpur, they're looking for experience, empathy and results. Dr. Vinita Malhotra has been treating women in Saharanpur since 1996 and is recognised across Lybrate, Justdial and the local community for thorough, compassionate care.",
    primaryKeyword: "best gynaecologist in Saharanpur",
    keywords: [
      "best gynaecologist in Saharanpur",
      "top gynaecologist Saharanpur",
      "best lady doctor Saharanpur",
      "best gynae clinic Saharanpur",
    ],
    schemaType: "MedicalSpecialty",
    services: [
      { title: "25+ Years of Experience", description: "Practicing since 1996 with thousands of deliveries, surgeries and consultations across Saharanpur." },
      { title: "Comprehensive Care Under One Roof", description: "Pregnancy, gynaecology, infertility, vaginal surgery and women's health — without referrals across hospitals." },
      { title: "Personalised Treatment", description: "Plans built around your age, lifestyle and family goals — not one-size-fits-all prescriptions." },
      { title: "Highly Rated Locally", description: "Strong word-of-mouth, repeat families and consistent ratings on third-party platforms like Lybrate and Justdial." },
      { title: "Virtual + In-Person", description: "In-person at Prakashpuram or online consultation when travel isn't practical." },
      { title: "Transparent Pricing", description: "Clinic fee and procedure costs shared up front. No hidden charges." },
    ],
    whenToVisit: [
      "You want a second opinion from a senior specialist.",
      "You've been getting conflicting advice from different doctors.",
      "You need an experienced doctor for a complex pregnancy or surgery.",
      "You want a long-term women's health partner you can stay with.",
    ],
    treatmentApproach: [
      "Time-tested clinical experience combined with current treatment guidelines.",
      "Conservative first — surgery only when clearly indicated.",
      "Honest counselling about success rates, risks and alternatives.",
      "Continuity of care from the same doctor across every visit.",
    ],
    faqs: [
      { q: "What makes Dr. Vinita Malhotra one of the best gynaecologists in Saharanpur?", a: "A combination of 25+ years of focused women's healthcare practice in Saharanpur, expertise across obstetrics, gynaecology and vaginal surgery, and an unhurried, patient-first consulting style." },
      { q: "How can I check reviews before booking?", a: "Public reviews are available on Lybrate (118+ ratings) and Justdial (63+ ratings). You can also ask the clinic for patient references during your visit." },
      { q: "Can I get a second opinion?", a: "Yes. Many patients come for a second opinion before surgery or fertility treatment — please bring your reports and prescriptions to make the visit useful." },
      ...COMMON_FAQS,
    ],
    ctaHeading: "Looking for the Best Gynaecologist in Saharanpur?",
    ctaSubheading: "Book a consultation with Dr. Vinita Malhotra — trusted by women in Saharanpur since 1996.",
  },
  {
    slug: "best-gynecologist-saharanpur",
    title: "Best Gynecologist in Saharanpur | Dr. Vinita Malhotra | Shanti Nursing Home",
    description:
      "Best gynecologist in Saharanpur — Dr. Vinita Malhotra, 25+ years experience. Pregnancy, PCOS, infertility, vaginal surgery, menopause care. In-person & online consultations.",
    h1: "Best Gynecologist in Saharanpur",
    intro:
      "Choosing the best gynecologist in Saharanpur isn't just about ratings — it's about finding someone who listens, explains and stays with you. Dr. Vinita Malhotra has built that kind of practice at Shanti Nursing Home since 1996.",
    primaryKeyword: "best gynecologist in Saharanpur",
    keywords: ["best gynecologist in Saharanpur", "top gynecologist Saharanpur", "best women's doctor Saharanpur"],
    schemaType: "MedicalSpecialty",
    services: [
      { title: "Senior Specialist", description: "Decades of experience handling routine and complex women's health cases in Saharanpur." },
      { title: "End-to-End Pregnancy Care", description: "From first positive test through postnatal recovery, including high-risk pregnancies." },
      { title: "Advanced Vaginal Surgery", description: "Special expertise in vaginal surgery — a niche skill that few clinics in Saharanpur offer." },
      { title: "Infertility & PCOS", description: "Comprehensive evaluation, hormonal management and treatment planning." },
      { title: "Menopause & Hormonal Care", description: "Evidence-based hormone therapy guidance, bone health and lifestyle support." },
      { title: "Preventive Health", description: "Pap smears, cancer screening, vaccinations and well-woman exams." },
    ],
    whenToVisit: [
      "You want a long-term women's health doctor, not a one-time visit.",
      "You're navigating a complex diagnosis (fibroid, PCOS, infertility, high-risk pregnancy).",
      "You want clear, jargon-free explanations of your reports.",
      "You need a doctor who's available for follow-ups by WhatsApp.",
    ],
    treatmentApproach: [
      "First visit focused on listening — full history before any prescription.",
      "Investigations only when they change the plan.",
      "Written prescriptions and treatment goals — no guesswork.",
      "Easy follow-up via WhatsApp for non-urgent questions.",
    ],
    faqs: [
      { q: "How is Shanti Nursing Home different from a multispecialty hospital?", a: "We are a dedicated women's health clinic — the doctor knows every patient personally and consultations are unhurried. There's no shuffling between specialists for women's concerns." },
      { q: "Can I see Dr. Vinita Malhotra for a one-off issue?", a: "Yes, absolutely. Many patients come in once for a specific problem (period pain, infection, second opinion) and decide later if they want ongoing care." },
      ...COMMON_FAQS,
    ],
    ctaHeading: "Find the Best Gynecologist in Saharanpur",
    ctaSubheading: "Schedule your visit with Dr. Vinita Malhotra at Shanti Nursing Home.",
  },
  {
    slug: "gynecologist-clinic-saharanpur",
    title: "Gynecologist Clinic in Saharanpur | Shanti Nursing Home | Dr. Vinita Malhotra",
    description:
      "Dedicated gynecology clinic in Saharanpur led by Dr. Vinita Malhotra. Women-only, private, well-equipped clinic on Circular Road, Prakashpuram. Walk in or book online.",
    h1: "Trusted Gynecologist Clinic in Saharanpur",
    intro:
      "Shanti Nursing Home is a dedicated gynecology clinic in Saharanpur, focused exclusively on women's health. Patients get the privacy of a small clinic with the experience of a senior specialist — Dr. Vinita Malhotra has run this practice since 1996.",
    primaryKeyword: "gynecologist clinic in Saharanpur",
    keywords: ["gynecologist clinic Saharanpur", "ladies clinic Saharanpur", "women's clinic Saharanpur", "Shanti Nursing Home"],
    schemaType: "MedicalSpecialty",
    services: [
      { title: "Private, Women-Focused Setting", description: "A calm, women-centric environment — no crowded multispecialty waiting rooms." },
      { title: "On-Site Examination Rooms", description: "Equipped for routine and procedural gynaecological exams, Pap smears and minor procedures." },
      { title: "Same-Doctor Continuity", description: "You see Dr. Vinita Malhotra on every visit — not a rotating panel." },
      { title: "Convenient Hours", description: "Two daily sessions (morning + evening) Mon–Sat plus Sunday by appointment." },
      { title: "WhatsApp Follow-Up", description: "Short clinical questions answered between visits via WhatsApp." },
      { title: "Central Saharanpur Location", description: "Easy to reach from Court Road, Delhi Road, Ambala Road and surrounding areas." },
    ],
    whenToVisit: [
      "You want a clinic that's specifically for women's health.",
      "You prefer a small private clinic over a large hospital outpatient department.",
      "You want short waiting times.",
      "You need a clinic in central Saharanpur close to public transport.",
    ],
    treatmentApproach: [
      "Same-day appointments wherever possible.",
      "Direct doctor consultation — no junior doctor screening first.",
      "Reports reviewed with you in the room, not via SMS.",
      "Clear paper trail: written diagnosis, prescription and follow-up date.",
    ],
    faqs: [
      { q: "Do I need to book in advance?", a: "Walk-ins are welcome but booking ahead means much shorter waiting. Call +91-9410805042 or WhatsApp to book." },
      { q: "Is parking available?", a: "Yes — street parking is available right outside, and the clinic is on the main Circular Road so auto and e-rickshaws can drop you at the entrance." },
      { q: "What should I bring on my first visit?", a: "Bring any past reports, prescriptions, ultrasound CDs and a list of current medicines. Period dates from the last 3 cycles are helpful too." },
      ...COMMON_FAQS,
    ],
    ctaHeading: "Visit Saharanpur's Trusted Gynae Clinic",
    ctaSubheading: "Book a slot at Shanti Nursing Home — Circular Road, Prakashpuram, Saharanpur.",
  },
  {
    slug: "gynecologist-saharanpur",
    title: "Gynecologist in Saharanpur | Dr. Vinita Malhotra | Shanti Nursing Home",
    description:
      "Senior gynecologist in Saharanpur. Dr. Vinita Malhotra (MBBS, DGO) provides expert care in obstetrics, gynecology, infertility, vaginal surgery & women's health since 1996.",
    h1: "Experienced Gynecologist in Saharanpur",
    intro:
      "Need a senior gynecologist in Saharanpur? Dr. Vinita Malhotra has been practicing women's healthcare since 1996, with deep experience across obstetrics, gynecology, infertility evaluation and vaginal surgery.",
    primaryKeyword: "gynecologist in Saharanpur",
    keywords: ["gynecologist in Saharanpur", "Saharanpur gynecologist", "Dr. Vinita Malhotra gynecologist"],
    schemaType: "MedicalSpecialty",
    services: [
      { title: "Routine & Preventive Care", description: "Annual exams, Pap smears, breast checks and vaccinations." },
      { title: "Period & PCOS Problems", description: "Diagnosis and management of irregular periods, heavy bleeding and PCOS." },
      { title: "Pregnancy Care", description: "Antenatal, delivery and postnatal care for both low- and high-risk pregnancies." },
      { title: "Infertility Workup", description: "Initial evaluation and treatment plan for couples trying to conceive." },
      { title: "Vaginal Surgery", description: "Special expertise in vaginal surgical procedures with decades of practice." },
      { title: "Menopause Care", description: "Symptom management, bone health and hormone therapy guidance." },
    ],
    whenToVisit: [
      "You haven't had a gynae checkup in over a year.",
      "Your period or hormonal pattern has changed.",
      "You're pregnant or planning a pregnancy.",
      "You have unexplained pelvic pain or vaginal discomfort.",
    ],
    treatmentApproach: [
      "Senior-led consultations — same doctor every visit.",
      "Conservative care first, surgery only when clearly indicated.",
      "Plain-language explanations of every report.",
      "WhatsApp follow-up for non-urgent questions.",
    ],
    faqs: [
      { q: "Can I see the gynecologist the same day?", a: "Same-day appointments are usually available during clinic hours. Call or WhatsApp ahead to confirm a slot." },
      { q: "What conditions does Dr. Vinita Malhotra treat?", a: "All common gynaecological concerns — periods, PCOS, infections, fibroids, infertility — plus pregnancy care, vaginal surgery, breast issues and urinary problems in women." },
      ...COMMON_FAQS,
    ],
    ctaHeading: "Book a Gynecologist in Saharanpur",
    ctaSubheading: "Schedule a visit with Dr. Vinita Malhotra at Shanti Nursing Home today.",
  },
  {
    slug: "ladies-doctor-saharanpur",
    title: "Ladies Doctor in Saharanpur | Female Gynaecologist | Dr. Vinita Malhotra",
    description:
      "Looking for a ladies doctor in Saharanpur? Consult Dr. Vinita Malhotra, female gynaecologist & obstetrician with 25+ years experience. Private, women-only clinic.",
    h1: "Ladies Doctor in Saharanpur",
    intro:
      "Many women in Saharanpur specifically prefer a lady doctor — for comfort, privacy and ease of conversation. Dr. Vinita Malhotra is a female gynaecologist and obstetrician practicing in Saharanpur since 1996.",
    primaryKeyword: "ladies doctor in Saharanpur",
    keywords: ["ladies doctor Saharanpur", "lady gynaecologist Saharanpur", "female gynaecologist Saharanpur", "mahila doctor Saharanpur"],
    schemaType: "MedicalSpecialty",
    services: [
      { title: "Female Specialist", description: "Comfortable, women-only consultation environment." },
      { title: "All Women's Health Concerns", description: "Periods, PCOS, infections, pregnancy, contraception, menopause." },
      { title: "Adolescent Care", description: "First period support, painful periods and adolescent hygiene counselling." },
      { title: "Pregnancy & Delivery", description: "From positive test to postnatal — including high-risk pregnancies." },
      { title: "Confidential Visits", description: "Private exam rooms, female assistants, complete confidentiality." },
      { title: "Family-Friendly", description: "Pediatric companion-friendly setup — bring your toddler if needed." },
    ],
    whenToVisit: [
      "You specifically want a female doctor.",
      "You're embarrassed or unsure how to talk about a symptom.",
      "You want adolescent care for a daughter.",
      "You want a long-term relationship with one doctor.",
    ],
    treatmentApproach: [
      "Female doctor + female assistants for every exam.",
      "Unhurried first visits — most consultations are 15–30 minutes.",
      "Sensitive topics handled without judgement.",
      "Clear, written instructions in plain language.",
    ],
    faqs: [
      { q: "Is the entire team female?", a: "Yes — Dr. Vinita Malhotra is supported by female nursing and clinical assistants for all examinations." },
      { q: "Can I bring my mother / husband / sister to the consultation?", a: "Of course. We welcome family members. We'll just ask for a moment of privacy during the physical examination if that's part of the visit." },
      ...COMMON_FAQS,
    ],
    ctaHeading: "Book a Lady Doctor in Saharanpur",
    ctaSubheading: "Schedule a confidential visit with Dr. Vinita Malhotra today.",
  },
  {
    slug: "obstetrician-saharanpur",
    title: "Obstetrician in Saharanpur | Pregnancy Specialist | Dr. Vinita Malhotra",
    description:
      "Trusted obstetrician in Saharanpur for safe pregnancy care. Dr. Vinita Malhotra (MBBS, DGO) — antenatal, high-risk pregnancy, normal delivery & C-section care since 1996.",
    h1: "Experienced Obstetrician in Saharanpur",
    intro:
      "A safe pregnancy starts with the right obstetrician. Dr. Vinita Malhotra has been delivering babies safely in Saharanpur since 1996 and personally manages each pregnancy from the first scan to postnatal recovery.",
    primaryKeyword: "obstetrician in Saharanpur",
    keywords: ["obstetrician in Saharanpur", "pregnancy doctor Saharanpur", "maternity doctor Saharanpur", "OB-GYN Saharanpur"],
    schemaType: "MedicalSpecialty",
    services: [
      { title: "Antenatal (Prenatal) Care", description: "Scheduled checkups, growth scans, blood pressure, weight and nutrition monitoring." },
      { title: "High-Risk Pregnancy Management", description: "Hypertension, diabetes, thyroid, previous loss, age-related and twin pregnancies." },
      { title: "Normal & Assisted Delivery", description: "Vaginal delivery, episiotomy, painless labour guidance where appropriate." },
      { title: "Caesarean Section", description: "C-section when medically indicated, with clear counselling and follow-up." },
      { title: "Postnatal Care", description: "Mother's recovery, lactation support, contraception and 6-week checkup." },
      { title: "Recurrent Pregnancy Loss", description: "Detailed evaluation, anti-coagulation where indicated and supportive care for the next pregnancy." },
    ],
    symptoms: [
      "Missed period and positive pregnancy test",
      "Severe morning sickness, dehydration or weight loss",
      "Vaginal bleeding or spotting during pregnancy",
      "Severe abdominal pain or cramping",
      "Reduced fetal movements after 24 weeks",
      "Swelling of feet/hands with headache (preeclampsia signs)",
    ],
    whenToVisit: [
      "You've had a positive pregnancy test — first visit should be within the first 6–8 weeks.",
      "You have any high-risk factor: hypertension, diabetes, thyroid, age over 35, prior loss.",
      "You're planning a pregnancy and want a preconception checkup.",
      "You've had two or more miscarriages.",
    ],
    treatmentApproach: [
      "Personalised antenatal schedule based on your specific risk profile.",
      "Same doctor across every visit — continuity is critical in pregnancy.",
      "24/7 reachability for labour, bleeding or other emergencies.",
      "Honest counselling on normal delivery vs. C-section based only on medical indication.",
    ],
    faqs: [
      { q: "When should I see an obstetrician for the first time?", a: "Ideally within 6–8 weeks of a missed period, or sooner if you have any bleeding, pain or known risk factors." },
      { q: "Will Dr. Vinita Malhotra personally do my delivery?", a: "Yes. Dr. Malhotra personally handles deliveries for her patients. In rare emergencies, a trusted backup is arranged in advance." },
      { q: "Is normal delivery possible after a previous C-section?", a: "VBAC (vaginal birth after caesarean) may be possible in selected cases. It depends on the reason for the previous C-section, the scar type and your current pregnancy. We'll review your prior records and discuss honestly." },
      ...COMMON_FAQS,
    ],
    ctaHeading: "Need an Obstetrician in Saharanpur?",
    ctaSubheading: "Start your pregnancy care with Dr. Vinita Malhotra at Shanti Nursing Home.",
  },
  {
    slug: "obstetrics-gynecology-saharanpur",
    title: "Obstetrics & Gynecology in Saharanpur | OB-GYN | Dr. Vinita Malhotra",
    description:
      "Complete obstetrics & gynecology care in Saharanpur. Pregnancy, delivery, infertility, PCOS, vaginal surgery, menopause & women's health — all by Dr. Vinita Malhotra.",
    h1: "Obstetrics & Gynecology in Saharanpur",
    intro:
      "Shanti Nursing Home offers full-spectrum obstetrics & gynecology (OB-GYN) services in Saharanpur. Whether it's your first pregnancy, an irregular period or a planned surgery — one experienced doctor handles all of it.",
    primaryKeyword: "obstetrics and gynecology in Saharanpur",
    keywords: ["obstetrics and gynecology Saharanpur", "OB-GYN Saharanpur", "obstetrics gynaecology clinic Saharanpur"],
    schemaType: "MedicalSpecialty",
    services: [
      { title: "Obstetrics (Pregnancy)", description: "Antenatal, intrapartum and postnatal care for normal and high-risk pregnancies." },
      { title: "General Gynecology", description: "Periods, PCOS, infections, fibroids, cysts, contraception and routine screening." },
      { title: "Infertility Evaluation", description: "Couple workup, hormonal testing, ovulation tracking, treatment planning." },
      { title: "Vaginal & Gynae Surgery", description: "Vaginal hysterectomy, repair surgeries, polypectomy and other minor/major procedures." },
      { title: "Menopause & Adolescent Health", description: "Care across every stage of a woman's life." },
      { title: "Preventive Screening", description: "Pap smear, breast exam, vaccinations and cancer screening counselling." },
    ],
    whenToVisit: [
      "You want one doctor for both pregnancy and gynaecology care.",
      "You need OB-GYN services for an ongoing condition.",
      "You're looking for a long-term women's health clinic.",
    ],
    treatmentApproach: [
      "Single point of contact across pregnancy + gynae care.",
      "Coordinated planning for surgeries, deliveries and follow-ups.",
      "Modern guidelines + decades of clinical judgement.",
      "Patient education at every step.",
    ],
    faqs: [
      { q: "What's the difference between obstetrics and gynecology?", a: "Obstetrics deals with pregnancy and childbirth. Gynecology deals with the female reproductive system in non-pregnant states. OB-GYNs are trained in both." },
      { q: "Is a single doctor for both safe?", a: "Yes — having one OB-GYN across your reproductive life means continuity, complete history and faster, better decisions." },
      ...COMMON_FAQS,
    ],
    ctaHeading: "Looking for an OB-GYN in Saharanpur?",
    ctaSubheading: "Book a consultation with Dr. Vinita Malhotra at Shanti Nursing Home.",
  },
  {
    slug: "pregnancy-care-saharanpur",
    title: "Pregnancy Care in Saharanpur | Antenatal & Maternity | Dr. Vinita Malhotra",
    description:
      "Complete pregnancy care in Saharanpur. Antenatal checkups, scans, nutrition, high-risk pregnancy & delivery by Dr. Vinita Malhotra at Shanti Nursing Home. Book online.",
    h1: "Pregnancy Care in Saharanpur",
    intro:
      "Pregnancy is a journey — and the right partner matters. Dr. Vinita Malhotra offers complete pregnancy care in Saharanpur, with personalised antenatal schedules, scans, nutrition support and delivery planning from week 6 to postnatal recovery.",
    primaryKeyword: "pregnancy care in Saharanpur",
    keywords: ["pregnancy care Saharanpur", "pregnancy doctor Saharanpur", "antenatal care Saharanpur", "maternity care Saharanpur"],
    schemaType: "MedicalProcedure",
    services: [
      { title: "First Trimester Care", description: "Confirmation, dating scan, folic acid, nausea management and early risk screening." },
      { title: "Routine Antenatal Visits", description: "Weight, BP, foetal heart, growth scans and trimester-specific blood work." },
      { title: "Anomaly & Growth Scans", description: "Targeted ultrasound at 11–13, 18–22 and 28–32 weeks." },
      { title: "Nutrition & Lifestyle", description: "Diet plans for healthy weight gain, gestational diabetes risk and iron levels." },
      { title: "Labour Preparation", description: "Birth plan, what to pack, signs of labour and pain management options." },
      { title: "Postnatal Care", description: "Recovery, breastfeeding support and the 6-week mother + baby checkup." },
    ],
    symptoms: [
      "Missed period and positive pregnancy test",
      "Severe nausea or vomiting",
      "Bleeding or spotting",
      "Lower abdominal pain or cramps",
      "Reduced foetal movements",
      "Severe headache or sudden swelling",
    ],
    whenToVisit: [
      "First positive pregnancy test (book within 6–8 weeks).",
      "You have hypertension, diabetes or thyroid problems.",
      "You're over 35 or had previous pregnancy complications.",
      "Any bleeding, pain or unusual symptom during pregnancy.",
    ],
    treatmentApproach: [
      "Customised antenatal visit schedule based on your risk profile.",
      "Same doctor across every visit — full continuity from week 6 to delivery.",
      "Clear week-by-week guidance with written instructions.",
      "Direct phone / WhatsApp access for urgent concerns.",
    ],
    faqs: [
      { q: "How many antenatal visits will I need?", a: "Most healthy pregnancies need 8–12 visits across 9 months. High-risk pregnancies may need more frequent monitoring." },
      { q: "Which scans are essential?", a: "Dating scan (6–9 weeks), NT scan (11–13 weeks), anomaly scan (18–22 weeks) and growth scans in the third trimester are the core scans for most pregnancies." },
      { q: "Can I continue my job during pregnancy?", a: "Most women can. We'll guide you based on your work intensity, travel needs and any pregnancy complications." },
      ...COMMON_FAQS,
    ],
    ctaHeading: "Start Your Pregnancy Care in Saharanpur",
    ctaSubheading: "Book your first antenatal visit with Dr. Vinita Malhotra at Shanti Nursing Home.",
  },
  {
    slug: "prenatal-care-saharanpur",
    title: "Prenatal Care in Saharanpur | Antenatal Checkups | Dr. Vinita Malhotra",
    description:
      "Comprehensive prenatal (antenatal) care in Saharanpur. Regular checkups, scans, nutrition guidance and pregnancy planning with Dr. Vinita Malhotra at Shanti Nursing Home.",
    h1: "Prenatal Care in Saharanpur",
    intro:
      "Good prenatal care reduces complications and gives you confidence through every trimester. Dr. Vinita Malhotra provides a complete prenatal care plan in Saharanpur — visits, scans, nutrition and birth preparation, all in one place.",
    primaryKeyword: "prenatal care in Saharanpur",
    keywords: ["prenatal care Saharanpur", "antenatal checkup Saharanpur", "pregnancy checkup Saharanpur"],
    schemaType: "MedicalProcedure",
    services: [
      { title: "Preconception Counselling", description: "Folic acid, vaccinations, BMI optimisation, control of any pre-existing condition." },
      { title: "First Trimester Screening", description: "Dating, NT scan, double marker and early risk assessment." },
      { title: "Second Trimester Care", description: "Anomaly scan, quadruple marker (if indicated), gestational diabetes screening." },
      { title: "Third Trimester Monitoring", description: "Growth scans, foetal well-being, blood pressure and labour planning." },
      { title: "Nutrition & Supplements", description: "Iron, calcium, folic acid and DHA guidance based on your labs." },
      { title: "Vaccinations", description: "Tdap and flu vaccines as per current Indian guidelines." },
    ],
    whenToVisit: [
      "You're planning a pregnancy (preconception visit).",
      "You've just tested positive — visit within 6–8 weeks.",
      "You missed a routine antenatal visit.",
      "You have new symptoms between scheduled visits.",
    ],
    treatmentApproach: [
      "Trimester-specific visit plan.",
      "Investigations matched to your risk — no unnecessary tests.",
      "Same doctor across every prenatal visit.",
      "Patient diary / hand-held card so you always have your record.",
    ],
    faqs: [
      { q: "Is prenatal care the same as antenatal care?", a: "Yes — both terms describe care given during pregnancy before delivery." },
      { q: "When should the first prenatal visit happen?", a: "Within 6–8 weeks of a missed period, or earlier if you have any risk factor or symptom." },
      ...COMMON_FAQS,
    ],
    ctaHeading: "Book Your Prenatal Visit",
    ctaSubheading: "Start safe pregnancy care with Dr. Vinita Malhotra at Shanti Nursing Home.",
  },
  {
    slug: "postnatal-care-saharanpur",
    title: "Postnatal Care in Saharanpur | After Delivery Care | Dr. Vinita Malhotra",
    description:
      "Postnatal care in Saharanpur — recovery, lactation support, contraception, mood and 6-week checkup by Dr. Vinita Malhotra. Care for both mother & baby after delivery.",
    h1: "Postnatal Care in Saharanpur",
    intro:
      "The first six weeks after delivery shape your long-term recovery. Dr. Vinita Malhotra provides structured postnatal care in Saharanpur covering physical healing, breastfeeding, contraception and mental health.",
    primaryKeyword: "postnatal care in Saharanpur",
    keywords: ["postnatal care Saharanpur", "post delivery care Saharanpur", "post pregnancy care Saharanpur", "lactation support Saharanpur"],
    schemaType: "MedicalProcedure",
    services: [
      { title: "Physical Recovery", description: "Perineal / C-section wound care, abdominal recovery, pelvic floor guidance." },
      { title: "Breastfeeding Support", description: "Latch, supply, sore nipples, blocked ducts and weaning advice." },
      { title: "6-Week Checkup", description: "Examination, contraception planning, return-to-exercise and return-to-work guidance." },
      { title: "Postnatal Contraception", description: "All options including IUCD, pills, condoms and counselling for breastfeeding mothers." },
      { title: "Mood & Sleep", description: "Screening for postpartum blues and depression — referral when needed." },
      { title: "Nutrition", description: "Diet plan for recovery, iron levels and lactation support." },
    ],
    symptoms: [
      "Persistent heavy bleeding beyond 4 weeks",
      "Fever or foul-smelling discharge",
      "Wound pain, redness or discharge",
      "Breast pain, lumps or fever (mastitis signs)",
      "Persistent low mood, anxiety or sleep problems",
      "Severe back pain or urinary leakage",
    ],
    whenToVisit: [
      "You delivered recently and want a structured 6-week checkup.",
      "You have wound, bleeding or breastfeeding issues.",
      "You want to plan contraception after delivery.",
      "You feel persistently low or anxious after delivery.",
    ],
    treatmentApproach: [
      "Scheduled postnatal visits at 1, 3 and 6 weeks.",
      "Lactation support included in routine visits.",
      "Mental health screening at the 6-week visit.",
      "Family planning planned together with your partner.",
    ],
    faqs: [
      { q: "When is the 6-week postnatal checkup important?", a: "It's a comprehensive review of physical recovery, breastfeeding, mental health and contraception — many problems are caught early at this visit." },
      { q: "Can I take contraception while breastfeeding?", a: "Yes — there are several safe options. We'll discuss what suits your situation best." },
      ...COMMON_FAQS,
    ],
    ctaHeading: "Book Postnatal Care in Saharanpur",
    ctaSubheading: "Schedule your post-delivery checkup with Dr. Vinita Malhotra.",
  },
  {
    slug: "high-risk-pregnancy-saharanpur",
    title: "High-Risk Pregnancy Doctor in Saharanpur | Dr. Vinita Malhotra",
    description:
      "Expert high-risk pregnancy care in Saharanpur. Hypertension, diabetes, thyroid, twin pregnancy, age 35+, previous loss — managed by Dr. Vinita Malhotra since 1996.",
    h1: "High-Risk Pregnancy Care in Saharanpur",
    intro:
      "A high-risk pregnancy doesn't have to mean a high-stress pregnancy. Dr. Vinita Malhotra has managed complex pregnancies in Saharanpur for over 25 years — with careful planning, close monitoring and clear communication, most high-risk pregnancies end with a healthy mother and baby.",
    primaryKeyword: "high-risk pregnancy doctor in Saharanpur",
    keywords: ["high risk pregnancy Saharanpur", "high risk pregnancy doctor Saharanpur", "complicated pregnancy Saharanpur", "twin pregnancy Saharanpur"],
    schemaType: "MedicalCondition",
    relatedConditions: ["Gestational Hypertension", "Gestational Diabetes", "Preeclampsia", "Recurrent Pregnancy Loss", "Twin Pregnancy"],
    services: [
      { title: "Hypertension in Pregnancy", description: "BP monitoring, medication planning, preeclampsia screening and management." },
      { title: "Gestational Diabetes", description: "OGTT screening, diet plan, sugar monitoring and insulin titration where needed." },
      { title: "Thyroid in Pregnancy", description: "TSH monitoring, dose adjustment of thyroxine, foetal monitoring." },
      { title: "Recurrent Pregnancy Loss", description: "Detailed workup, anticoagulation, supportive medication and frequent scans." },
      { title: "Twin / Multiple Pregnancy", description: "Closer scan schedule, growth tracking and tailored delivery planning." },
      { title: "Advanced Maternal Age", description: "Tailored screening, more frequent visits and proactive risk management." },
    ],
    symptoms: [
      "Severe headache or visual disturbance",
      "Swelling of face and hands",
      "Sudden weight gain in pregnancy",
      "BP > 140/90 readings",
      "High blood sugar readings",
      "Reduced foetal movement",
      "Bleeding or fluid leak before due date",
    ],
    whenToVisit: [
      "You have BP, diabetes or thyroid problems before or during pregnancy.",
      "You are over 35 or have had a previous loss / preterm delivery.",
      "You're carrying twins or triplets.",
      "Your scan or report has flagged a concern.",
    ],
    treatmentApproach: [
      "Risk profile mapped at the first visit.",
      "Closer monitoring schedule — more visits and more scans.",
      "Coordinated care with internal medicine / endocrinology when needed.",
      "Clear delivery plan made in advance, not in an emergency.",
    ],
    faqs: [
      { q: "Does a high-risk pregnancy always mean C-section?", a: "No. Many high-risk pregnancies still deliver vaginally. The mode of delivery depends on the specific risk factor and your condition at term." },
      { q: "Can I travel during a high-risk pregnancy?", a: "Sometimes yes, sometimes no — it depends on the trimester and your specific risk. Please ask before travelling." },
      { q: "Will I need to be admitted?", a: "Most high-risk pregnancies are managed on an outpatient basis. Admission is reserved for severe BP, bleeding or other acute concerns." },
      ...COMMON_FAQS,
    ],
    ctaHeading: "Need a High-Risk Pregnancy Doctor in Saharanpur?",
    ctaSubheading: "Book a consultation with Dr. Vinita Malhotra — experienced in complex pregnancies since 1996.",
  },
  {
    slug: "maternity-hospital-saharanpur",
    title: "Maternity Hospital in Saharanpur | Shanti Nursing Home | Dr. Vinita Malhotra",
    description:
      "Trusted maternity hospital in Saharanpur. Safe delivery, antenatal & postnatal care by Dr. Vinita Malhotra. Personal attention, experienced doctor, central Saharanpur location.",
    h1: "Maternity Hospital in Saharanpur",
    intro:
      "Shanti Nursing Home is a small, focused maternity hospital in Saharanpur — not a large general hospital where you're a number. Patients get personal attention from Dr. Vinita Malhotra from the first scan through delivery and postnatal recovery.",
    primaryKeyword: "maternity hospital in Saharanpur",
    keywords: ["maternity hospital Saharanpur", "delivery hospital Saharanpur", "best maternity hospital Saharanpur", "nursing home Saharanpur"],
    schemaType: "MedicalSpecialty",
    services: [
      { title: "Normal Delivery", description: "Vaginal delivery with supportive labour, episiotomy when needed and skin-to-skin contact after birth." },
      { title: "Caesarean Section", description: "C-section with experienced surgical team when medically indicated." },
      { title: "Painless Labour Guidance", description: "Counselling on pain relief options during labour where suitable." },
      { title: "24/7 Doctor Availability", description: "Dr. Vinita Malhotra is on call for her patients during labour." },
      { title: "Newborn First Care", description: "Immediate newborn care and breastfeeding initiation." },
      { title: "Postnatal Stay", description: "Comfortable rooms and supportive nursing care during recovery." },
    ],
    whenToVisit: [
      "You want a small, personal maternity setting rather than a busy multispecialty hospital.",
      "You want the same doctor through antenatal + delivery + postnatal.",
      "You want a maternity hospital in central Saharanpur.",
    ],
    treatmentApproach: [
      "Senior obstetrician personally handles labour & delivery.",
      "Honest, evidence-based counselling on normal delivery vs. C-section.",
      "Clean, private postnatal rooms with attendant access.",
      "Newborn care and breastfeeding support from day 1.",
    ],
    faqs: [
      { q: "Will the same doctor who saw me through pregnancy do my delivery?", a: "Yes. Dr. Vinita Malhotra personally manages deliveries for her patients, with a trusted backup arranged in advance for rare emergencies." },
      { q: "Do you have NICU?", a: "Shanti Nursing Home does not have an in-house NICU. For high-risk neonatal cases, we coordinate with a partner NICU facility in Saharanpur." },
      { q: "What about painless delivery (epidural)?", a: "We counsel patients on labour pain management options and arrange them where appropriate. Please discuss preferences during antenatal visits." },
      ...COMMON_FAQS,
    ],
    ctaHeading: "Plan Your Delivery at Shanti Nursing Home",
    ctaSubheading: "Book an antenatal visit with Dr. Vinita Malhotra to plan your delivery.",
  },
  {
    slug: "normal-delivery-c-section-saharanpur",
    title: "Normal Delivery & C-Section in Saharanpur | Dr. Vinita Malhotra",
    description:
      "Safe normal delivery & C-section in Saharanpur by Dr. Vinita Malhotra. Honest counselling on mode of delivery, experienced surgeon, 24/7 doctor availability for labour.",
    h1: "Normal Delivery & C-Section in Saharanpur",
    intro:
      "Choosing between normal delivery and a C-section can feel overwhelming. Dr. Vinita Malhotra gives you the medical facts honestly — and recommends what's safest for you and your baby, not what's easier to schedule.",
    primaryKeyword: "normal delivery and C-section in Saharanpur",
    keywords: ["normal delivery Saharanpur", "C-section Saharanpur", "caesarean Saharanpur", "VBAC Saharanpur", "painless delivery Saharanpur"],
    schemaType: "MedicalProcedure",
    services: [
      { title: "Normal (Vaginal) Delivery", description: "Supportive labour, episiotomy when needed, immediate skin-to-skin contact and breastfeeding initiation." },
      { title: "Caesarean Section", description: "Planned or emergency C-section with experienced surgical care and detailed postoperative monitoring." },
      { title: "VBAC Counselling", description: "Honest assessment for vaginal birth after a previous C-section in selected cases." },
      { title: "Painless Labour Guidance", description: "Counselling on epidural analgesia and other pain-relief options for labour." },
      { title: "Twin Delivery", description: "Personalised delivery planning for twin pregnancies based on presentation and gestation." },
      { title: "Postnatal Recovery", description: "Wound care, mobilisation, lactation support and discharge counselling." },
    ],
    whenToVisit: [
      "You want honest counselling on mode of delivery.",
      "You had a previous C-section and want to discuss VBAC.",
      "You're 36+ weeks and want to finalise a birth plan.",
      "You have a condition that may affect delivery (placenta previa, breech, twins, etc.).",
    ],
    treatmentApproach: [
      "Mode of delivery decided by medical indication — not convenience.",
      "Full disclosure of risks and benefits before any decision.",
      "Birth plan documented in advance with the patient.",
      "24/7 doctor availability for labour calls.",
    ],
    faqs: [
      { q: "Is normal delivery safer than C-section?", a: "When safely possible, yes — vaginal delivery generally has shorter recovery and lower surgical risk. But when there's a clear medical indication, C-section is the safer choice." },
      { q: "What is the C-section rate at the clinic?", a: "We don't aim for a target rate. The C-section is performed when medically required — most commonly for foetal distress, failure to progress, breech presentation or repeat C-section indications." },
      { q: "Can I have VBAC (normal delivery after C-section)?", a: "VBAC is possible in selected cases — depending on the previous scar type, reason for the previous C-section and your current pregnancy. We'll review your old records and discuss honestly." },
      { q: "Is painless delivery (epidural) available?", a: "We counsel on labour pain management options and arrange epidural analgesia where appropriate. Please raise this preference during antenatal visits so we can plan." },
      ...COMMON_FAQS,
    ],
    ctaHeading: "Plan Your Safe Delivery in Saharanpur",
    ctaSubheading: "Discuss your birth plan with Dr. Vinita Malhotra at Shanti Nursing Home.",
  },
  {
    slug: "maternal-healthcare-saharanpur",
    title: "Maternal Healthcare in Saharanpur | Mother & Baby Care | Dr. Vinita Malhotra",
    description:
      "Complete maternal healthcare in Saharanpur — preconception, pregnancy, delivery, postnatal & breastfeeding support by Dr. Vinita Malhotra at Shanti Nursing Home.",
    h1: "Maternal Healthcare in Saharanpur",
    intro:
      "Maternal healthcare doesn't begin in the labour room — it starts before you even conceive. Dr. Vinita Malhotra offers complete maternal healthcare in Saharanpur covering preconception planning, pregnancy, safe delivery and postnatal recovery.",
    primaryKeyword: "maternal healthcare in Saharanpur",
    keywords: ["maternal healthcare Saharanpur", "mother and baby care Saharanpur", "pregnancy and postnatal care Saharanpur"],
    schemaType: "MedicalSpecialty",
    services: [
      { title: "Preconception Counselling", description: "Folic acid, weight, control of chronic conditions and vaccination review." },
      { title: "Pregnancy Care", description: "Antenatal visits, scans, nutrition and high-risk pregnancy management." },
      { title: "Safe Delivery", description: "Vaginal delivery or C-section, decided by medical indication." },
      { title: "Postnatal Care", description: "Recovery, breastfeeding, contraception and 6-week mother + baby checkup." },
      { title: "Iron & Nutrition", description: "Anaemia treatment, calcium, iron and protein guidance through pregnancy." },
      { title: "Mental Wellbeing", description: "Screening for antenatal anxiety and postpartum depression." },
    ],
    whenToVisit: [
      "You're planning a pregnancy.",
      "You're pregnant and want comprehensive maternal care.",
      "You've just delivered and want postnatal support.",
      "You want a coordinated mother + baby plan.",
    ],
    treatmentApproach: [
      "Same doctor across preconception, pregnancy and postnatal stages.",
      "Holistic plan: nutrition, exercise, mental health and physical care.",
      "Patient-held records so you carry your history with you.",
      "WhatsApp follow-up between visits.",
    ],
    faqs: [
      { q: "When should maternal healthcare start?", a: "Ideally 3 months before trying to conceive — with folic acid, BMI optimisation and a checkup. If that's not possible, the first antenatal visit by 6–8 weeks is essential." },
      ...COMMON_FAQS,
    ],
    ctaHeading: "Start Your Maternal Health Journey",
    ctaSubheading: "Book a visit with Dr. Vinita Malhotra at Shanti Nursing Home.",
  },
  {
    slug: "infertility-treatment-saharanpur",
    title: "Infertility Treatment in Saharanpur | Dr. Vinita Malhotra | Shanti Nursing Home",
    description:
      "Infertility evaluation & treatment in Saharanpur. Hormonal testing, ovulation tracking, PCOS management, basic treatments & counselling by Dr. Vinita Malhotra. Book today.",
    h1: "Infertility Treatment in Saharanpur",
    intro:
      "Trouble conceiving is more common than most couples realise — and very often, it's treatable. Dr. Vinita Malhotra offers structured infertility evaluation and treatment in Saharanpur, with a clear step-by-step plan and honest counselling about success rates.",
    primaryKeyword: "infertility treatment in Saharanpur",
    keywords: ["infertility treatment Saharanpur", "infertility doctor Saharanpur", "infertility specialist Saharanpur", "fertility clinic Saharanpur"],
    schemaType: "MedicalCondition",
    relatedConditions: ["Female Infertility", "Anovulation", "PCOS", "Tubal Factor Infertility"],
    services: [
      { title: "Couple Evaluation", description: "Detailed history, examination and basic workup for both partners." },
      { title: "Hormonal Testing", description: "FSH, LH, AMH, TSH, prolactin and other indicated hormones." },
      { title: "Ovulation Tracking", description: "Follicular monitoring scans to confirm ovulation and time intercourse correctly." },
      { title: "PCOS-Related Infertility", description: "Weight, metformin, ovulation induction and lifestyle plan." },
      { title: "Tubal & Uterine Evaluation", description: "HSG, ultrasound and referral for hysterosalpingography or hysteroscopy where indicated." },
      { title: "Onward Referral", description: "Coordinated referral to IVF / advanced ART centres when needed." },
    ],
    symptoms: [
      "Trying to conceive for 12+ months without success (or 6 months if age 35+)",
      "Irregular or absent periods",
      "Known PCOS, endometriosis or thyroid problems",
      "History of pelvic infection or surgery",
      "Recurrent miscarriage",
      "Male partner with known fertility concerns",
    ],
    whenToVisit: [
      "Under 35 and trying for over a year without success.",
      "Age 35+ and trying for over 6 months.",
      "You have known PCOS, endometriosis or irregular cycles.",
      "You've had two or more miscarriages.",
    ],
    treatmentApproach: [
      "Both partners evaluated — fertility is never just a woman's issue.",
      "Conservative first: lifestyle, ovulation tracking, ovulation induction.",
      "Honest counselling about realistic success rates at each step.",
      "Clear, written treatment plan and timeline.",
    ],
    faqs: [
      { q: "How long should we try before seeing an infertility doctor?", a: "If you're under 35 — try for 12 months. If 35 or older — try for 6 months. See us sooner if you have known PCOS, irregular periods or prior pelvic surgery." },
      { q: "Will I need IVF?", a: "Most couples don't. Many conceive with simple steps — ovulation induction, timed intercourse, treating PCOS or thyroid. IVF is reserved for specific cases." },
      { q: "Is infertility evaluation expensive?", a: "Basic evaluation is affordable. We order tests step-by-step rather than a long expensive panel up front." },
      { q: "Is the husband / male partner also evaluated?", a: "Yes — a basic semen analysis for the male partner is part of any couple's infertility workup." },
      ...COMMON_FAQS,
    ],
    ctaHeading: "Start Your Fertility Journey",
    ctaSubheading: "Book a couple consultation with Dr. Vinita Malhotra at Shanti Nursing Home.",
  },
  {
    slug: "pcod-pcos-treatment-saharanpur",
    title: "PCOD / PCOS Treatment in Saharanpur | Dr. Vinita Malhotra",
    description:
      "PCOS / PCOD treatment in Saharanpur. Period regulation, weight & insulin care, acne and hair management, fertility support by Dr. Vinita Malhotra. Long-term care plan.",
    h1: "PCOD / PCOS Treatment in Saharanpur",
    intro:
      "PCOD (or PCOS) affects 1 in 5 Indian women — and it can affect periods, weight, skin, hair and fertility. Dr. Vinita Malhotra offers structured PCOS treatment in Saharanpur with a long-term plan rather than short-term pills.",
    primaryKeyword: "PCOS treatment in Saharanpur",
    keywords: ["PCOS treatment Saharanpur", "PCOD treatment Saharanpur", "PCOS doctor Saharanpur", "irregular periods Saharanpur"],
    schemaType: "MedicalCondition",
    relatedConditions: ["Polycystic Ovary Syndrome", "PCOD", "Insulin Resistance", "Anovulation"],
    services: [
      { title: "Diagnosis", description: "Symptoms + ultrasound + blood work to confirm PCOS using current criteria." },
      { title: "Period Regulation", description: "Cyclic medication or hormonal therapy to restore predictable periods." },
      { title: "Weight & Insulin Care", description: "Metformin, lifestyle and nutrition plan to address insulin resistance." },
      { title: "Acne & Hair", description: "Targeted medication for acne, unwanted facial hair and scalp hair loss." },
      { title: "Fertility Support", description: "Ovulation induction for couples trying to conceive." },
      { title: "Long-Term Monitoring", description: "Annual review of sugar, lipids, BP and uterine lining." },
    ],
    symptoms: [
      "Irregular or absent periods",
      "Unwanted facial or body hair",
      "Persistent acne or oily skin",
      "Sudden weight gain — especially around the belly",
      "Difficulty conceiving",
      "Scalp hair thinning",
      "Skin darkening on neck or underarms (acanthosis)",
    ],
    whenToVisit: [
      "Your periods are unpredictable or skipping.",
      "You've gained weight rapidly without lifestyle change.",
      "You have facial hair, acne or hair loss together.",
      "You've been trying to conceive without success.",
    ],
    treatmentApproach: [
      "PCOS is managed long-term, not 'cured' in one visit.",
      "Lifestyle first — sleep, diet, movement.",
      "Targeted medication for the specific bother (periods, fertility, acne).",
      "Annual screening for diabetes and cholesterol once diagnosed.",
    ],
    faqs: [
      { q: "Is PCOD the same as PCOS?", a: "They overlap but aren't identical. PCOD often refers to polycystic ovary appearance on scan; PCOS is the broader syndrome with hormonal and metabolic features. Treatment principles overlap." },
      { q: "Can PCOS be cured?", a: "PCOS isn't cured but it's very controllable. Most symptoms respond well to a combination of lifestyle and targeted medication." },
      { q: "Will PCOS prevent me from getting pregnant?", a: "No, most women with PCOS can conceive — sometimes naturally, sometimes with help. We'll guide you when you're ready to try." },
      { q: "Do I need to take medication forever?", a: "Not necessarily. Many women come off medication once their cycles, weight and symptoms stabilise on lifestyle changes." },
      ...COMMON_FAQS,
    ],
    ctaHeading: "Start PCOS Treatment in Saharanpur",
    ctaSubheading: "Book a PCOS consultation with Dr. Vinita Malhotra at Shanti Nursing Home.",
  },
  {
    slug: "menopause-management-saharanpur",
    title: "Menopause Management in Saharanpur | Dr. Vinita Malhotra",
    description:
      "Menopause care in Saharanpur — hot flashes, mood changes, bone health, hormone therapy guidance & long-term wellbeing by Dr. Vinita Malhotra at Shanti Nursing Home.",
    h1: "Menopause Management in Saharanpur",
    intro:
      "Menopause is a natural stage — but it doesn't have to be a difficult one. Dr. Vinita Malhotra provides structured menopause management in Saharanpur covering symptoms, bone health, hormone therapy guidance and long-term wellbeing.",
    primaryKeyword: "menopause management in Saharanpur",
    keywords: ["menopause Saharanpur", "menopause doctor Saharanpur", "perimenopause Saharanpur", "hot flashes treatment Saharanpur"],
    schemaType: "MedicalCondition",
    relatedConditions: ["Menopause", "Perimenopause", "Osteoporosis", "Vasomotor Symptoms"],
    services: [
      { title: "Perimenopause Symptom Care", description: "Hot flashes, night sweats, mood swings, sleep problems and irregular periods." },
      { title: "Hormone Therapy Guidance", description: "Evidence-based decisions on whether MHT is right for you, with risk-benefit counselling." },
      { title: "Bone Health", description: "Calcium, vitamin D and DEXA scan guidance to prevent osteoporosis." },
      { title: "Heart & Metabolic Health", description: "Blood pressure, cholesterol and weight management post-menopause." },
      { title: "Vaginal Dryness & Intimacy", description: "Local treatment options for dryness and discomfort." },
      { title: "Mental Wellbeing", description: "Screening for anxiety and mood changes around menopause." },
    ],
    symptoms: [
      "Irregular periods or periods stopping",
      "Hot flashes and night sweats",
      "Sleep problems",
      "Mood swings, anxiety or low mood",
      "Vaginal dryness or discomfort",
      "Joint pain or fatigue",
      "Memory or concentration problems",
    ],
    whenToVisit: [
      "Your periods have changed in your 40s.",
      "You have hot flashes that affect daily life.",
      "You're 12 months without a period and want a checkup.",
      "You have a family history of osteoporosis or heart disease.",
    ],
    treatmentApproach: [
      "Personalised symptom assessment — not everyone needs hormones.",
      "Lifestyle first — exercise, calcium, sleep and stress management.",
      "Hormone therapy only when benefits clearly outweigh risks.",
      "Long-term plan for bone and heart health.",
    ],
    faqs: [
      { q: "What's the average age of menopause in India?", a: "Around 46–48 years in India, slightly earlier than the global average. Perimenopausal symptoms can start years before." },
      { q: "Is hormone therapy safe?", a: "Hormone therapy (MHT) is safe and effective for many women under 60 with significant symptoms — but it's individualised. We discuss risks and benefits in detail." },
      { q: "Can menopause cause weight gain?", a: "Yes — metabolism slows and fat tends to shift around the abdomen. Strength training and dietary changes help." },
      ...COMMON_FAQS,
    ],
    ctaHeading: "Get Menopause Care in Saharanpur",
    ctaSubheading: "Book a menopause consultation with Dr. Vinita Malhotra.",
  },
  {
    slug: "vaginal-surgery-saharanpur",
    title: "Vaginal Surgery in Saharanpur | Dr. Vinita Malhotra | Shanti Nursing Home",
    description:
      "Specialised vaginal surgery in Saharanpur. Vaginal hysterectomy, prolapse repair, cyst & polyp removal by Dr. Vinita Malhotra — surgeon with 25+ years experience.",
    h1: "Vaginal Surgery in Saharanpur",
    intro:
      "Vaginal surgery is a niche surgical skill — and Dr. Vinita Malhotra is one of the few specialists in Saharanpur who performs it regularly. Vaginal route surgery offers shorter recovery, no abdominal scar and faster return to daily life for suitable cases.",
    primaryKeyword: "vaginal surgery in Saharanpur",
    keywords: ["vaginal surgery Saharanpur", "vaginal hysterectomy Saharanpur", "prolapse surgery Saharanpur", "vaginal surgeon Saharanpur"],
    schemaType: "MedicalProcedure",
    services: [
      { title: "Vaginal Hysterectomy", description: "Removal of the uterus through the vaginal route — no abdominal scar, faster recovery in suitable cases." },
      { title: "Prolapse Repair", description: "Repair of cystocele, rectocele and uterine prolapse via the vaginal route." },
      { title: "Vaginal Cyst & Polyp Removal", description: "Day-care removal of benign cysts and polyps under appropriate anaesthesia." },
      { title: "Perineal Repair", description: "Repair of old perineal tears or episiotomy-related issues." },
      { title: "Tightening / Repair Surgery", description: "Reconstructive procedures for post-delivery laxity in selected cases." },
      { title: "Preoperative Counselling", description: "Clear discussion of indications, alternatives, risks and recovery." },
    ],
    symptoms: [
      "Something coming down (mass) at the vagina",
      "Heaviness or pressure in the pelvis",
      "Difficulty emptying bladder or bowel",
      "Stress urinary incontinence with prolapse",
      "Heavy bleeding requiring hysterectomy",
      "Persistent vaginal lump or cyst",
    ],
    whenToVisit: [
      "You've been told you need a hysterectomy and want a less invasive route.",
      "You have pelvic organ prolapse.",
      "You have a vaginal cyst or polyp that needs removal.",
      "You want a second opinion before any open surgery.",
    ],
    treatmentApproach: [
      "Surgery only after conservative options are tried (where appropriate).",
      "Detailed preoperative counselling — risks, alternatives, recovery.",
      "Vaginal route preferred where suitable for faster recovery.",
      "Structured postoperative follow-up.",
    ],
    faqs: [
      { q: "What's the advantage of vaginal surgery over open surgery?", a: "No abdominal scar, less postoperative pain, shorter hospital stay and faster return to daily activities — in suitable cases." },
      { q: "How long is the recovery after a vaginal hysterectomy?", a: "Most women return to light activities within 2–3 weeks and full activity within 6 weeks. Heavy lifting is avoided for about 6 weeks." },
      { q: "Is vaginal surgery painful?", a: "Surgery is done under anaesthesia. Postoperative discomfort is manageable with standard pain medication and is typically less than with open surgery." },
      ...COMMON_FAQS,
    ],
    ctaHeading: "Need Vaginal Surgery in Saharanpur?",
    ctaSubheading: "Book a surgical consultation with Dr. Vinita Malhotra at Shanti Nursing Home.",
  },
  {
    slug: "vaginal-surgeon-saharanpur",
    title: "Vaginal Surgeon in Saharanpur | Dr. Vinita Malhotra | 25+ Years Experience",
    description:
      "Experienced vaginal surgeon in Saharanpur — Dr. Vinita Malhotra performs vaginal hysterectomy, prolapse repair and other vaginal-route surgeries with 25+ years experience.",
    h1: "Experienced Vaginal Surgeon in Saharanpur",
    intro:
      "Vaginal surgery requires a surgeon who has done it many times — confidently and routinely. Dr. Vinita Malhotra has performed vaginal-route surgeries in Saharanpur since 1996 and is one of the few specialists in the region with this focused skill set.",
    primaryKeyword: "vaginal surgeon in Saharanpur",
    keywords: ["vaginal surgeon Saharanpur", "lady surgeon Saharanpur", "experienced gynae surgeon Saharanpur"],
    schemaType: "MedicalSpecialty",
    services: [
      { title: "Vaginal Hysterectomy", description: "Removal of the uterus via the vaginal route." },
      { title: "Prolapse Surgery", description: "Anterior, posterior and apical compartment repairs." },
      { title: "Reconstructive Surgery", description: "Post-delivery repairs and reconstructive procedures." },
      { title: "Day-Care Procedures", description: "Cyst removal, polypectomy and minor procedures with same-day discharge in many cases." },
      { title: "Preoperative Workup", description: "Detailed evaluation and counselling before any surgery." },
      { title: "Continuous Postoperative Care", description: "Same surgeon for surgery + follow-up." },
    ],
    whenToVisit: [
      "You've been advised hysterectomy and want a vaginal-route option.",
      "You have pelvic organ prolapse.",
      "You want a senior, experienced female surgeon.",
    ],
    treatmentApproach: [
      "Experience-driven decision-making — same surgeon at every step.",
      "Vaginal route preferred where it serves the patient better.",
      "Honest discussion of when open or laparoscopic surgery is the better choice.",
      "Personal postoperative follow-up.",
    ],
    faqs: [
      { q: "How many vaginal surgeries has Dr. Malhotra performed?", a: "Across 25+ years of practice in Saharanpur, Dr. Malhotra has performed a high volume of vaginal-route surgeries — please ask during your consultation for specifics on your procedure." },
      ...COMMON_FAQS,
    ],
    ctaHeading: "Consult an Experienced Vaginal Surgeon",
    ctaSubheading: "Book a surgical consultation with Dr. Vinita Malhotra at Shanti Nursing Home.",
  },
  {
    slug: "gynecological-surgery-saharanpur",
    title: "Gynecological Surgery in Saharanpur | Dr. Vinita Malhotra | Shanti Nursing Home",
    description:
      "Gynecological surgery in Saharanpur — vaginal hysterectomy, prolapse repair, cyst & polyp removal and more. Experienced gynae surgeon, transparent counselling.",
    h1: "Gynecological Surgery in Saharanpur",
    intro:
      "Some gynaecological problems need surgery — fibroids that bleed heavily, persistent cysts, prolapse, severe endometriosis. Dr. Vinita Malhotra offers gynecological surgery in Saharanpur with honest counselling about when surgery helps and when it doesn't.",
    primaryKeyword: "gynecological surgery in Saharanpur",
    keywords: ["gynecological surgery Saharanpur", "gynae surgery Saharanpur", "uterus surgery Saharanpur", "fibroid surgery Saharanpur"],
    schemaType: "MedicalProcedure",
    services: [
      { title: "Hysterectomy", description: "Removal of uterus — vaginal route preferred where suitable; otherwise abdominal." },
      { title: "Ovarian Cyst Surgery", description: "Cystectomy or oophorectomy when a cyst is large, complex or symptomatic." },
      { title: "Fibroid Surgery", description: "Myomectomy or hysterectomy depending on age, family plans and symptom load." },
      { title: "Prolapse Repair", description: "Vaginal repair of cystocele, rectocele and uterine prolapse." },
      { title: "D&C / Polyp Removal", description: "Diagnostic and therapeutic D&C, endometrial polyp removal." },
      { title: "Ectopic Pregnancy Management", description: "Emergency surgical or medical management as indicated." },
    ],
    whenToVisit: [
      "You have heavy bleeding, severe pain or a known fibroid / cyst.",
      "You've been advised surgery and want a second opinion.",
      "You have prolapse symptoms.",
      "You want to discuss surgical vs. non-surgical options.",
    ],
    treatmentApproach: [
      "Surgery only when clearly indicated — and only after conservative options are honestly assessed.",
      "Detailed preoperative counselling on what surgery does and doesn't fix.",
      "Vaginal / minimally invasive route preferred where suitable.",
      "Personal follow-up till complete recovery.",
    ],
    faqs: [
      { q: "Do all fibroids need surgery?", a: "No — only fibroids that cause symptoms (heavy bleeding, pressure, infertility) or are very large typically need surgery. Many small, asymptomatic fibroids can simply be monitored." },
      { q: "Will hysterectomy affect my hormones / sex life?", a: "Hysterectomy alone (uterus removed, ovaries preserved) does not cause menopause. We discuss all such concerns in detail before any surgery." },
      ...COMMON_FAQS,
    ],
    ctaHeading: "Plan Your Gynae Surgery in Saharanpur",
    ctaSubheading: "Book a surgical consultation with Dr. Vinita Malhotra at Shanti Nursing Home.",
  },
  {
    slug: "gynecological-checkup-saharanpur",
    title: "Gynecological Checkup in Saharanpur | Well-Woman Exam | Dr. Vinita Malhotra",
    description:
      "Annual gynecological checkup in Saharanpur — Pap smear, breast exam, ultrasound, blood work & preventive screening by Dr. Vinita Malhotra. Book a well-woman visit.",
    h1: "Annual Gynecological Checkup in Saharanpur",
    intro:
      "A yearly gynae checkup catches problems early — when they're easiest to treat. Dr. Vinita Malhotra offers structured well-woman exams in Saharanpur with the right screening for your age, lifestyle and family history.",
    primaryKeyword: "gynecological checkup in Saharanpur",
    keywords: ["gynae checkup Saharanpur", "well woman exam Saharanpur", "Pap smear Saharanpur", "preventive women's health Saharanpur"],
    schemaType: "MedicalProcedure",
    services: [
      { title: "Pap Smear", description: "Cervical cancer screening at age-appropriate intervals." },
      { title: "Breast Examination", description: "Clinical breast exam + mammography referral when indicated." },
      { title: "Pelvic Examination", description: "Examination for any masses, infection or prolapse." },
      { title: "Pelvic Ultrasound", description: "Ovarian, uterine and endometrial check where indicated." },
      { title: "Blood Tests", description: "Haemoglobin, sugar, thyroid and lipids — based on age and risk." },
      { title: "Lifestyle Counselling", description: "Nutrition, weight, sleep and exercise guidance." },
    ],
    whenToVisit: [
      "You haven't had a gynae checkup in over a year.",
      "You're between 21–65 — yearly checkup is recommended.",
      "You have a family history of breast, ovarian or cervical cancer.",
      "You're planning a pregnancy and want a preconception checkup.",
    ],
    treatmentApproach: [
      "Age- and risk-matched screening — no unnecessary tests.",
      "Single visit covers history, exam and required tests.",
      "Reports reviewed with you, not by SMS.",
      "Written plan for any abnormal finding.",
    ],
    faqs: [
      { q: "How often do I need a Pap smear?", a: "Most women need a Pap smear every 3 years from age 21 to 65 (more often if previous abnormal results). We'll personalise the schedule for you." },
      { q: "Are these checkups painful?", a: "A pelvic exam and Pap smear cause brief discomfort but are not painful. We explain each step before starting." },
      ...COMMON_FAQS,
    ],
    ctaHeading: "Book Your Annual Gynae Checkup",
    ctaSubheading: "Schedule a well-woman visit with Dr. Vinita Malhotra at Shanti Nursing Home.",
  },
  {
    slug: "womens-health-clinic-saharanpur",
    title: "Women's Health Clinic in Saharanpur | Dr. Vinita Malhotra | Shanti Nursing Home",
    description:
      "Dedicated women's health clinic in Saharanpur covering periods, pregnancy, fertility, menopause, breast & urinary care by Dr. Vinita Malhotra. Private, women-focused clinic.",
    h1: "Women's Health Clinic in Saharanpur",
    intro:
      "Women's health doesn't fit into a single specialty — it covers periods, pregnancy, fertility, menopause, breast and urinary care, plus mental wellbeing. Shanti Nursing Home brings all of this under one trusted clinic in Saharanpur.",
    primaryKeyword: "women's health clinic in Saharanpur",
    keywords: ["women's health clinic Saharanpur", "women's clinic Saharanpur", "ladies clinic Saharanpur", "female health Saharanpur"],
    schemaType: "MedicalSpecialty",
    services: [
      { title: "Reproductive Health", description: "Periods, PCOS, contraception and family planning." },
      { title: "Pregnancy & Postnatal", description: "Antenatal, delivery and postnatal recovery." },
      { title: "Breast Health", description: "Examination, screening counselling and referral for mammography." },
      { title: "Urinary Issues", description: "Recurrent UTI, stress incontinence and overactive bladder counselling." },
      { title: "Menopause & Bone Health", description: "Symptom care, hormone therapy guidance and osteoporosis prevention." },
      { title: "Mental Wellbeing", description: "Screening for antenatal anxiety, postpartum depression and perimenopause mood changes." },
    ],
    whenToVisit: [
      "You want a single clinic for all women's health needs.",
      "You have multiple concerns to discuss in one visit.",
      "You want to build a long-term relationship with one doctor.",
    ],
    treatmentApproach: [
      "Holistic — body + hormones + mental wellbeing.",
      "Long-term continuity with the same doctor.",
      "Coordinated care across pregnancy, gynae and menopause.",
      "Whole-family-friendly setup.",
    ],
    faqs: [
      { q: "Can I discuss multiple issues in one visit?", a: "Yes — please make a list before you come so we can prioritise and cover the important concerns thoroughly." },
      ...COMMON_FAQS,
    ],
    ctaHeading: "Visit Saharanpur's Women's Health Clinic",
    ctaSubheading: "Book a consultation at Shanti Nursing Home with Dr. Vinita Malhotra.",
  },
  {
    slug: "womens-healthcare-saharanpur",
    title: "Women's Healthcare in Saharanpur | Dr. Vinita Malhotra | Shanti Nursing Home",
    description:
      "Complete women's healthcare in Saharanpur — every life stage from adolescence to menopause. Dr. Vinita Malhotra (MBBS, DGO) — practicing since 1996.",
    h1: "Women's Healthcare in Saharanpur",
    intro:
      "Women's healthcare changes through life — and the right doctor changes with you. Dr. Vinita Malhotra offers complete women's healthcare in Saharanpur from your first period through pregnancy, parenting and menopause.",
    primaryKeyword: "women's healthcare in Saharanpur",
    keywords: ["women's healthcare Saharanpur", "women's health Saharanpur", "ladies healthcare Saharanpur"],
    schemaType: "MedicalSpecialty",
    services: [
      { title: "Adolescent Care", description: "First period, irregular cycles, painful periods, hygiene and counselling." },
      { title: "Reproductive Years", description: "Contraception, fertility, pregnancy, infections and screening." },
      { title: "Pregnancy & Motherhood", description: "Pregnancy care, delivery, postnatal recovery and breastfeeding support." },
      { title: "Midlife", description: "Heavy periods, fibroids, cysts, perimenopause." },
      { title: "Menopause & Beyond", description: "Symptom care, hormone guidance, bone and heart health." },
      { title: "Preventive Care", description: "Vaccinations, Pap smear, breast and lifestyle counselling." },
    ],
    whenToVisit: [
      "You want one doctor for all life stages.",
      "You're entering a new stage (adolescence, pregnancy, menopause).",
      "You're due for any preventive screening.",
    ],
    treatmentApproach: [
      "Continuity across life stages.",
      "Same doctor for daughter, mother and grandmother in many families.",
      "Plain-language counselling at every visit.",
      "Holistic women's health — not just gynae problems.",
    ],
    faqs: [
      { q: "Do you see adolescent girls?", a: "Yes — adolescent girls are welcome with a parent. We address first-period concerns, painful periods, PCOS, vaccinations and general guidance." },
      ...COMMON_FAQS,
    ],
    ctaHeading: "Care Across Every Stage of Life",
    ctaSubheading: "Book with Dr. Vinita Malhotra at Shanti Nursing Home.",
  },
  {
    slug: "dr-vinita-malhotra",
    title: "Dr. Vinita Malhotra | Gynaecologist & Obstetrician | Saharanpur",
    description:
      "Meet Dr. Vinita Malhotra — MBBS, DGO. Senior gynaecologist, obstetrician & vaginal surgeon in Saharanpur. Practicing since 1996 at Shanti Nursing Home. Book online.",
    h1: "Dr. Vinita Malhotra — Gynaecologist & Obstetrician, Saharanpur",
    intro:
      "Dr. Vinita Malhotra is a senior gynaecologist, obstetrician and vaginal surgeon practicing in Saharanpur since 1996. She runs Shanti Nursing Home — a dedicated women's healthcare clinic on Circular Road, Prakashpuram.",
    primaryKeyword: "Dr. Vinita Malhotra",
    keywords: ["Dr. Vinita Malhotra", "Dr Vinita Malhotra Saharanpur", "Vinita Malhotra gynaecologist", "Shanti Nursing Home doctor"],
    schemaType: "MedicalSpecialty",
    services: [
      { title: "Qualifications", description: "MBBS, DGO — Obstetrician, Gynaecologist & Vaginal Surgeon." },
      { title: "Experience", description: "Practicing in Saharanpur since 1996 — over 25 years of women's healthcare." },
      { title: "Areas of Expertise", description: "Obstetrics, gynaecology, high-risk pregnancy, vaginal surgery, infertility, menopause." },
      { title: "Languages", description: "Fluent in Hindi and English." },
      { title: "Practice Location", description: "Shanti Nursing Home, Circular Road, Prakashpuram, Saharanpur." },
      { title: "Ratings", description: "Strong word-of-mouth in Saharanpur and consistent ratings on Lybrate and Justdial." },
    ],
    whenToVisit: [
      "You want a senior specialist for any women's health concern.",
      "You need an experienced obstetrician for a high-risk pregnancy.",
      "You've been advised gynae surgery and want an experienced surgeon.",
    ],
    treatmentApproach: [
      "Unhurried, listening-first consultations.",
      "Conservative care before surgery.",
      "Same doctor across every visit and procedure.",
      "Easy WhatsApp follow-up between visits.",
    ],
    faqs: [
      { q: "What are Dr. Vinita Malhotra's qualifications?", a: "MBBS, DGO — Obstetrician, Gynaecologist and Vaginal Surgeon." },
      { q: "How long has Dr. Vinita Malhotra been practicing?", a: "Since 1996 — over 25 years in Saharanpur." },
      { q: "Where is Dr. Vinita Malhotra's clinic?", a: "Shanti Nursing Home, Circular Road, Opposite Private Ward, SBD Hospital, Prakashpuram, Saharanpur 247001." },
      ...COMMON_FAQS,
    ],
    ctaHeading: "Consult Dr. Vinita Malhotra",
    ctaSubheading: "Book an in-person or online consultation at Shanti Nursing Home, Saharanpur.",
  },
  {
    slug: "dr-vinita-malhotra-saharanpur",
    title: "Dr. Vinita Malhotra Saharanpur | Gynaecologist & Obstetrician | Reviews & Booking",
    description:
      "Dr. Vinita Malhotra (MBBS, DGO) — senior gynaecologist & obstetrician in Saharanpur. Practicing since 1996. Reviews, fees, address, hours and online booking.",
    h1: "Dr. Vinita Malhotra, Gynaecologist in Saharanpur",
    intro:
      "Dr. Vinita Malhotra is a Saharanpur-based gynaecologist and obstetrician with over 25 years of practice. This page has everything you need — qualifications, address, hours, services, reviews and how to book.",
    primaryKeyword: "Dr. Vinita Malhotra Saharanpur",
    keywords: ["Dr Vinita Malhotra Saharanpur", "Vinita Malhotra obstetrician", "Vinita Malhotra gynaecologist Saharanpur", "Shanti Nursing Home doctor"],
    schemaType: "MedicalSpecialty",
    services: [
      { title: "Qualifications", description: "MBBS, DGO from recognised institutions." },
      { title: "Specialties", description: "Obstetrics, gynaecology, vaginal surgery, infertility, high-risk pregnancy." },
      { title: "Experience", description: "25+ years in Saharanpur since 1996." },
      { title: "Clinic Hours", description: "Mon–Sat 11 AM–3 PM and 6:30 PM–8 PM. Sun by appointment." },
      { title: "Languages", description: "Hindi and English." },
      { title: "Booking", description: "Online, phone or WhatsApp — same-day appointments usually available." },
    ],
    whenToVisit: [
      "You want a senior gynaecologist with proven experience.",
      "You need an experienced obstetrician for any pregnancy concern.",
      "You're seeking a long-term women's health specialist.",
    ],
    treatmentApproach: [
      "Same-doctor continuity.",
      "Honest, evidence-based counselling.",
      "Conservative-first; surgical when clearly needed.",
      "Easy WhatsApp follow-up.",
    ],
    faqs: [
      { q: "What is Dr. Vinita Malhotra's consultation fee?", a: "Affordable and transparent — please call +91-9410805042 or WhatsApp us for the current fee." },
      { q: "Does Dr. Vinita Malhotra take virtual appointments?", a: "Yes — virtual consultations are available by appointment." },
      ...COMMON_FAQS,
    ],
    ctaHeading: "Book Dr. Vinita Malhotra",
    ctaSubheading: "Schedule a visit at Shanti Nursing Home, Saharanpur.",
  },
]

export const seoPageBySlug: Record<string, SeoPage> = Object.fromEntries(
  seoPages.map((p) => [p.slug, p]),
)
